image:
  file: .gitpod.Dockerfile

# Command to start on workspace startup (optional)
tasks:
  - name: yarn
  - name: npm
  - name: node
  - name: git
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview